print('[-- Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele. --]\n')
a = input('Digite algo: ')
print(f'O tipo primitivo deste valor é {type(a)} ')
print(f'Só tem espaços? {a.isspace()}')
print(f'Só tem números? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'É maiúscula? {a.isupper()}')
print(f'É minúscula? {a.islower()}')
print(f'É capitalizada? {a.istitle()}')

